# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-25 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortner', '0006_auto_20181225_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='clickevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shortner_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shortner.shortnerURL')),
            ],
        ),
    ]
