# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-24 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortnerurl',
            name='shortcode',
            field=models.CharField(default='default', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
