# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-24 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_shortnerurl_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortnerurl',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortnerurl',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
