# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-24 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_auto_20181224_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortnerurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shortnerurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
