# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-24 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0004_auto_20181224_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortnerurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
