# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-25 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import shortner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0005_auto_20181225_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortnerurl',
            name='url',
            field=models.CharField(max_length=200, validators=[shortner.validators.validate_url, shortner.validators.validate_dot_com]),
        ),
    ]
